services:
  fuseki:
    container_name: fuseki
    image: secoresearch/fuseki
    restart: always
    ports:
      - "3030:3030"
    environment:
      - ADMIN_PASSWORD=admin
      - ENABLE_DATA_WRITE=true
      - ENABLE_UPDATE=true
      - ENABLE_UPLOAD=true
    volumes:
      - ./configuration:/fuseki-base/configuration/
      - ./data:/fuseki-base/databases/